from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2ca9a0a71965"
down_revision: str | Sequence[str] | None = "8ccc505cb77b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "uq_clock_events_user_client_event_id",
        "clock_events",
        ["user_id", "client_event_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_clock_events_user_client_event_id", table_name="clock_events")
    # ### end Alembic commands ###
