"""add day notes

Revision ID: 2f06e12c33fb
Revises: f2b2f58c0b23
Create Date: 2026-02-12 12:36:36.284756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f06e12c33fb'
down_revision: Union[str, Sequence[str], None] = 'f2b2f58c0b23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('day_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date_local', sa.Date(), nullable=False),
    sa.Column('content', sa.String(length=4000), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_day_notes_date_local'), 'day_notes', ['date_local'], unique=False)
    op.create_index(op.f('ix_day_notes_user_id'), 'day_notes', ['user_id'], unique=False)
    op.create_index('uq_day_notes_user_date', 'day_notes', ['user_id', 'date_local'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_day_notes_user_date', table_name='day_notes')
    op.drop_index(op.f('ix_day_notes_user_id'), table_name='day_notes')
    op.drop_index(op.f('ix_day_notes_date_local'), table_name='day_notes')
    op.drop_table('day_notes')
    # ### end Alembic commands ###
