from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "38b5bbf15b54"
down_revision: Union[str, Sequence[str], None] = "2ca9a0a71965"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "absence_reasons",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_absence_reasons_user_id"), "absence_reasons", ["user_id"], unique=False
    )
    op.create_index(
        "uq_absence_reasons_user_name",
        "absence_reasons",
        ["user_id", "name"],
        unique=True,
    )
    op.create_table(
        "absences",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("reason_id", sa.Integer(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["reason_id"], ["absence_reasons.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_absences_reason_id"), "absences", ["reason_id"], unique=False
    )
    op.create_index(op.f("ix_absences_user_id"), "absences", ["user_id"], unique=False)
    op.create_index(
        "ix_absences_user_start_end",
        "absences",
        ["user_id", "start_date", "end_date"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_absences_user_start_end", table_name="absences")
    op.drop_index(op.f("ix_absences_user_id"), table_name="absences")
    op.drop_index(op.f("ix_absences_reason_id"), table_name="absences")
    op.drop_table("absences")
    op.drop_index("uq_absence_reasons_user_name", table_name="absence_reasons")
    op.drop_index(op.f("ix_absence_reasons_user_id"), table_name="absence_reasons")
    op.drop_table("absence_reasons")
    # ### end Alembic commands ###
