from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8ccc505cb77b"
down_revision: Union[str, Sequence[str], None] = "2a5dc2bdc90f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clock_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("ts_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "type",
            sa.Enum("COME", "GO", "BREAK_START", "BREAK_END", name="clock_event_type"),
            nullable=False,
        ),
        sa.Column(
            "location", sa.Enum("HOME", "OFFICE", name="work_location"), nullable=True
        ),
        sa.Column("geo_lat", sa.Float(), nullable=True),
        sa.Column("geo_lng", sa.Float(), nullable=True),
        sa.Column("geo_accuracy_m", sa.Float(), nullable=True),
        sa.Column("client_event_id", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_clock_events_ts_utc"), "clock_events", ["ts_utc"], unique=False
    )
    op.create_index(
        op.f("ix_clock_events_user_id"), "clock_events", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_clock_events_user_id"), table_name="clock_events")
    op.drop_index(op.f("ix_clock_events_ts_utc"), table_name="clock_events")
    op.drop_table("clock_events")
    # ### end Alembic commands ###
